trigger:
  - dev
  - develop
  - master
  - cicd

resources:
  repositories:
    - repository: Pipelines
      type: git
      name: "Architecture/Siigo.Pipeline"
      ref: "refs/heads/dev"

extends:
  template: gateway/gateway-pipeline.yaml@Pipelines
  parameters:
    projectName: api-gateway-Siigo.Gateway.Payroll
    environment: aksdev
    namespace: siigo-payroll