trigger:
  - dev
  - master

resources:
  repositories:
    - repository: Pipelines
      type: git
      name: "Siigo/Siigo.Pipeline"
      ref: fix/architecture/default-feed

extends:

  template: node/node-library.yaml@Pipelines