trigger:
  - dev
  - master

resources:
  repositories:
    - repository: Pipelines
      type: git
      name: "Siigo/Siigo.Pipeline"
      ref: feature/arquitectura/node-library

extends:

  template: node/node-library.yaml@Pipelines