trigger:
  - dev
  - develop
  - master
  - cicd

resources:     
  - pipeline: Golang
    source: 'Siigo.Archetype.Golang.DDD CICD' # Change with the name of the source pipeline microservice
    trigger:
      branches:
        - refs/heads/master
  
  - pipeline: Csharp
    source: 'Siigo.Archetype.Csharp.DDD CICD' # Change with the name of the source pipeline microservice
    trigger:
      branches:
        - refs/heads/master
  
  repositories:
    - repository: Pipelines
      type: git
      name: "Siigo/Siigo.Pipeline"

extends:

  template: node/node-library.yaml@Pipelines