trigger:
  - dev
  - develop
  - master
  - cicd

resources:
  repositories:
    - repository: Pipelines
      type: git
      name: "Siigo/Siigo.Pipeline"

extends:

  template: node/node-library.yaml@Pipelines