trigger:
  - dev
  - develop
  - master
  - cicd

resources:
  
  pipelines:
  - pipeline: Parent
    source: 'Siigo.Archetype.Csharp.DDD CICD' # Change with the name of the source pipeline microservice
    project: 'Siigo'
    trigger:
      branches:
        - refs/heads/dev
        - refs/heads/master
  
  - pipeline: Parent
    source: 'Siigo.Archetype.Golang.DDD CICD' # Change with the name of the source pipeline microservice
    project: 'Siigo'
    trigger:
      branches:
        - refs/heads/dev
        - refs/heads/master
  
  repositories:
    - repository: Pipelines
      type: git
      name: "Siigo/Siigo.Pipeline"

extends:

  template: node/node-library.yaml@Pipelines