// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	example "siigo.com/<%= config.name %>/proto"
)

// IPersonRepository is an autogenerated mock type for the IPersonRepository type
type IPersonRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: person
func (_m *IPersonRepository) Save(person *example.PersonResource) (*example.PersonResource, error) {
	ret := _m.Called(person)

	var r0 *example.PersonResource
	if rf, ok := ret.Get(0).(func(*example.PersonResource) *example.PersonResource); ok {
		r0 = rf(person)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*example.PersonResource)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*example.PersonResource) error); ok {
		r1 = rf(person)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
