apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: my-test
spec:
  parallelism: 30
  script:
    configMap:
      name: my-test
      file: test.js
  separate: true
  arguments: "--out statsd -e ENV=qa -e TYPE=load"
  runner:
    env:
      - name: K6_STATSD_ADDR
        value: "52.247.86.112:8125"
      - name: K6_STATSD_ENABLE_TAGS
        value: "true"