// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeErrServer is an autogenerated mock type for the UnsafeErrServer type
type UnsafeErrServer struct {
	mock.Mock
}

// mustEmbedUnimplementedErrServer provides a mock function with given fields:
func (_m *UnsafeErrServer) mustEmbedUnimplementedErrServer() {
	_m.Called()
}
