// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafePersonServer is an autogenerated mock type for the UnsafePersonServer type
type UnsafePersonServer struct {
	mock.Mock
}

// mustEmbedUnimplementedPersonServer provides a mock function with given fields:
func (_m *UnsafePersonServer) mustEmbedUnimplementedPersonServer() {
	_m.Called()
}
