// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	context "context"

	example "siigo.com/bolt/proto"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// ErrClient is an autogenerated mock type for the ErrClient type
type ErrClient struct {
	mock.Mock
}

// Error provides a mock function with given fields: ctx, in, opts
func (_m *ErrClient) Error(ctx context.Context, in *example.HealthRequest, opts ...grpc.CallOption) (*example.HealthResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *example.HealthResponse
	if rf, ok := ret.Get(0).(func(context.Context, *example.HealthRequest, ...grpc.CallOption) *example.HealthResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*example.HealthResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *example.HealthRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
