// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeGreeterServer is an autogenerated mock type for the UnsafeGreeterServer type
type UnsafeGreeterServer struct {
	mock.Mock
}

// mustEmbedUnimplementedGreeterServer provides a mock function with given fields:
func (_m *UnsafeGreeterServer) mustEmbedUnimplementedGreeterServer() {
	_m.Called()
}
