trigger:
- master
- dev

resources:
  repositories:
    - repository: Pipelines
      type: git
      name: "Siigo/Siigo.Pipeline"
      ref: 'refs/heads/dev'

extends:
  template: netcore/dotnet-library.yaml@Pipelines

  parameters:
    projectName: Siigo.Core.<%= config.nameCapitalize %>
    feedSiigo: 'nuget'
    minCoverage: 0