FROM golang:1.16 as builder


ENV GIT_TERMINAL_PROMPT=1
ENV GOPRIVATE=dev.azure.com

RUN apt-get update \
    && apt-get install -y --no-install-recommends protobuf-compiler \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && go get -u github.com/cosmtrek/air

ENV LIBRDKAFKA_VERSION=1.5.3

RUN git clone https://github.com/edenhill/librdkafka.git && \
    cd librdkafka && \
    git checkout tags/v${LIBRDKAFKA_VERSION} && \
    ./configure --prefix=/usr && \
    make && \
    make install &&\
    ldconfig && \
    cd .. && \
    rm -rf librdkafka

ARG DEV_OPS_TOKEN

RUN git config --global url."https://anythinggoeshere:$DEV_OPS_TOKEN@dev.azure.com".insteadOf "https://dev.azure.com"

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download
