FROM golang:1.16 as builder


ENV GIT_TERMINAL_PROMPT=1
ENV LIBRDKAFKA_VERSION=1.5.3

ARG devops_token
ENV GOPRIVATE=dev.azure.com

RUN git clone https://github.com/edenhill/librdkafka.git && \
    cd librdkafka && \
    git checkout tags/v${LIBRDKAFKA_VERSION} && \
    ./configure --prefix=/usr && \
    make && \
    make install &&\
    ldconfig && \
    cd .. && \
    rm -rf librdkafka

RUN apt update && apt install protobuf-compiler -y && \
    go get -u github.com/cosmtrek/air

RUN git config --global url."https://anythinggoeshere:$devops_token@dev.azure.com".insteadOf "https://dev.azure.com"

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download
