// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	context "context"

	example "siigo.com/<%= config.name %>/proto"

	mock "github.com/stretchr/testify/mock"
)

// ErrServer is an autogenerated mock type for the ErrServer type
type ErrServer struct {
	mock.Mock
}

// Error provides a mock function with given fields: _a0, _a1
func (_m *ErrServer) Error(_a0 context.Context, _a1 *example.HealthRequest) (*example.HealthResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *example.HealthResponse
	if rf, ok := ret.Get(0).(func(context.Context, *example.HealthRequest) *example.HealthResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*example.HealthResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *example.HealthRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
