// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	context "context"

	example "siigo.com/<%= config.name %>/proto"

	mock "github.com/stretchr/testify/mock"
)

// GreeterServer is an autogenerated mock type for the GreeterServer type
type GreeterServer struct {
	mock.Mock
}

// Greeting provides a mock function with given fields: _a0, _a1
func (_m *GreeterServer) Greeting(_a0 context.Context, _a1 *example.GreetingRequest) (*example.GreetingResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *example.GreetingResponse
	if rf, ok := ret.Get(0).(func(context.Context, *example.GreetingRequest) *example.GreetingResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*example.GreetingResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *example.GreetingRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
