// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	context "context"

	example "siigo.com/<%= config.name %>/proto"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// GreeterClient is an autogenerated mock type for the GreeterClient type
type GreeterClient struct {
	mock.Mock
}

// Greeting provides a mock function with given fields: ctx, in, opts
func (_m *GreeterClient) Greeting(ctx context.Context, in *example.GreetingRequest, opts ...grpc.CallOption) (*example.GreetingResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *example.GreetingResponse
	if rf, ok := ret.Get(0).(func(context.Context, *example.GreetingRequest, ...grpc.CallOption) *example.GreetingResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*example.GreetingResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *example.GreetingRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
