trigger:
  - dev
  - develop
  - master

resources:
  repositories:
    - repository: Pipelines
      type: git
      name: 'Architecture/Siigo.Pipeline'
      ref: 'refs/heads/spark'

extends:
  template: spark/spark-pipeline.yaml@Pipelines
  parameters:
    projectName: job-<%= config.name %>-migration
