// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isHttpRule_Pattern is an autogenerated mock type for the isHttpRule_Pattern type
type isHttpRule_Pattern struct {
	mock.Mock
}

// isHttpRule_Pattern provides a mock function with given fields:
func (_m *isHttpRule_Pattern) isHttpRule_Pattern() {
	_m.Called()
}
