version: '3.9'

services:
  app:
    ports:
      - "5000:5000"
      - "6000:6000"
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
      args:
        # Update your personal access token and run "docker-compose up --build"
        - DEV_OPS_TOKEN=<%= config.token %>
    volumes:
    - ./:/app
    privileged: true
    stdin_open: true
    tty: true
    working_dir: /app
    entrypoint: make all