version: '3.9'

services:
  app:
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
      args:
        # replace for your personal access token
        - devops_token=<%= config.token %>
    volumes:
    - ./:/app
    privileged: true
    stdin_open: true
    tty: true
    working_dir: /app
    entrypoint: make all