# Default values for ak6.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# type of test
type: 'load'

# environment qa | preprod
environment: 'qa'

#  How many instances of k6 you want to create. Each instance will be assigned an equal execution segment. For instance,
# if your test script is configured to run 200 VUs and parallelism is set to 4, as in the example above,
# the operator will create four k6 jobs,
# each running 50 VUs to achieve the desired VU count.
parallelism: 10
