apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: ms-<%= config.nameUpper %>
  namespace: siigo-catalog
spec:
  scaleTargetRef:
    deploymentName: ms-<%= config.nameUpper %> # must be in the same namespace as the ScaledObject
    #containerName: {container-name}  #Optional. Default: deployment.spec.template.spec.containers[0]
  pollingInterval: 30  # Optional. Default: 30 seconds
  cooldownPeriod:  300 # Optional. Default: 300 seconds
  minReplicaCount: 2   # Optional. Default: 0
  maxReplicaCount: 30 # Optional. Default: 100
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: qakafka.siigo.com:9094
        topic: Spark<%= config.nameUpper %>MigrationFull
        consumerGroup: Spark<%= config.nameUpper %>Migration-Consumer-Group
        lagThreshold: '5'